services:
   node-dc-22:
      build:
         context: .
         dockerfile: node-dockerfile
         args:
            VARIANT: 22-bookworm
      image: node-dc-22
      volumes:
         - ..:/workspace:cached
      command: /bin/sh -c "tail -F a-file-that-does-not-exist"
